JAVA_URL=https://download.java.net/java/GA/jdk10/10.0.2/19aef61b38124481863b1413dce1855f/13/openjdk-10.0.2_linux-x64_bin.tar.gz
TOMCAT_URL=https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.65/bin/apache-tomcat-9.0.65.tar.gz
JAVA_HOME=/opt/jdk-10
TOMCAT_HOME=/opt/tomcat
PORT=8080
